### ISSUE TITLE
Fix errors on the home page displayed for a non-logged in user

### ISSUE THREAD

**Issue by mantasimkus** [pets-oss/pets-front#172]
Currently, recent animals and events are displayed on the home page only to a logged in user. Should a non-logged in user be able to see them too? If not, then no error messages (see the picture below) should appear on his/her screen.

![image](https://user-images.githubusercontent.com/80693723/117465622-8e0bfd80-af5a-11eb-84c3-b2f69d524b4b.png)

**Comment by rikius** [comment]
Please remove only error messages
