### ISSUE TITLE
Create UI of animal-list page

### ISSUE THREAD

**Issue by saulyz** [pets-oss/pets-front#28]
Animal listing can be implemented in various modes for various needs. So there should be a view selector. Like "more button" with dropdown selection of available options in chrome://bookmarks (example values: "list", "gallery", "datatable").
There might be useful to create View Service which could make views configurable, unified and flexible to use in various pages/scopes.

Select Animal props that are most relevant to the listing (example: name, picture, gender, specie, check-in-date, description, ..)
For result listing use the List - https://material-ui.com/components/lists/#align-list-items
Link each item to its own details page.
To reveal properties you might use avatar, icons, badges (check with latest design version)
No Pagination needed yet.

Move GraphQL data providing features to a separate (data-only) component. 
Add Loader Component while query is loading. Like here https://material-ui.com/components/backdrop/

**Comment by mantasgailius** [comment]
Design sketch of animal card for mobile and desktop version 
https://xd.adobe.com/view/1f2da00c-c0a0-44d6-b6ed-292f788e8567-4a7e/
