### ISSUE TITLE
Create search filters for Animal list page

### ISSUE THREAD

**Issue by saulyz** [pets-oss/pets-front#56]
Search filters will be used in a Page Top section (#55).
Search filters are merged with "Create new Animal" action, filtering result.
Responsive implementation (mobile, desktop) is very similar. Difference in mobile - we do not have create new as it is moved to Bottom Nav FAB.

By clicking filter icon, opens Search filter Dialog
Chips show what is currently in filters. User can close chip which changes filters value. Filters also can be changed by opening filter Dialog and interacting with inputs (react select). Should check with backend if multiple filter values are allowed.

Clicking outside Dialog would mean Cancel action.

Search filter dialog should be implemented the same for all screens. On mobile it should take the whole screen. No "close" icon.

**Comment by benNek** [comment]
design link: https://www.figma.com/file/gZ4w6nuUvZ4AlKSEQXKWM6/Untitled?node-id=5%3A613
