### ISSUE TITLE
Setup and deploy to Github pages

### ISSUE THREAD

**Issue by saulyz** [pets-oss/pets-front#7]
1) Configure Github Actions (deploy with PR merge). Create deploy.yml action file for that.
Check example with integration.yml in this repo and community created actions https://github.com/marketplace?type=actions for deployment.  

2) Deploy SPA to Github static pages
(do not solve 404 routing in this task)

**Comment by rikius** [comment]
There is another solution that we can do too, so we can push only on tag update.

```
on:
  push:
    tags:
      - '*'
```
