### ISSUE TITLE
User menu should close on navigating

### ISSUE THREAD

**Issue by saulyz** [pets-oss/pets-front#90]
When User menu opens - you can click “User profile” or “Logout”. If you choose “User profile”, user is redirected to the page, but menu stays open. It should close after click and navigation being possible.

![image](https://user-images.githubusercontent.com/12073767/112013207-8a4f2380-8b32-11eb-9f4c-38a67ddaf141.png)

**Comment by lukaskairys** [comment]
I believe that dialogue box should also appear below your account name, not over it.
